### ISSUE TITLE
Cannot see the other deactive tab

### ISSUE THREAD

**Issue by kotobuki09** [PROxZIMA/Sweet-Pop#10]
I am not sure what happened in my case but I cannot see other tab even though it there. I try to change to other theme but it's still able to see it. I am not installing Firefox Color.  
https://i.imgur.com/odRjdUD.png

Another issue that I got is that I cannot scroll on top when I used an arrow button to expand my bookmark tab. It's consistently kept at the bottom of the list

**Comment by PROxZIMA** [comment]
Hey!! Sorry for the extremely late reply but I've fixed the tab issue. It was due to `z-index`. You can view the latest [release](https://github.com/PROxZIMA/Sweet-Pop/releases/tag/3.1.0).

> Another issue that I got is that I cannot scroll on top when I used an arrow button to expand my bookmark tab. It's consistently kept at the bottom of the list

I didn't understand the issue properly. Could you please attach a screen recording of the issue. I'll try to replicate it on my end
