### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Siarune** [PROxZIMA/Sweet-Pop#17]
I have managed to get it installed at this point, but I wanted to point out a couple of problems in the install script (normal and curl)

The firefox folder variable has an unnecessary extra slash that may have been causing a problem but I found that it persistently printed a 1 before the profile directory name.

```
Profiles file found...
Failed to locate Profile folder at /home/aidan/.mozilla/firefox/1
25xn6287.default-release
Exiting...
```
I think it may be setting the variable to 1 and then printing the actual directory separately. But you know this better than I do.

Other than that small issue I think this is a really great project. Thank you and keep up the good work.

**Comment by PROxZIMA** [comment]
Can you post your `profiles.ini` file please?

As you can see here if `-p` argument is not provided then the script tries to extract the profile folder name from `profiles.ini`.

https://github.com/PROxZIMA/Sweet-Pop/blob/608d001e632f7b04bca126518c70c02cd081cc7c/programs/install.sh#L43-L47

In-short

```bash
$ grep 'Default=' $PROFILES_FILE | sed 's/^Default=//'
```

is the catch here. I'm still looking for a proper reliable way to get the default profile folder as `profiles.ini`'s content vary from one platform to other or from one Firefox version to other.

In my case `profiles.ini` looks something like this. That's why above command works.

```
[Install4F96D1932A9F858E]
Default=1yrah0xg.default-release
Locked=1
```

**Comment by PROxZIMA** [comment]
> Other than that small issue I think this is a really great project. Thank you and keep up the good work.

Thank you for the kind words 🙌

**Comment by Siarune** [comment]
You're welcome

My `profile.ini` is at `~/.mozilla/firefox/profiles.ini`. Not sure if Flatpak makes a difference in that.

```
[Profile1]
Name=default
IsRelative=1
Path=gx2dqpwy.default
Default=1

[Profile0]
Name=default-release
IsRelative=1
Path=25xn6287.default-release

[General]
StartWithLastProfile=1
Version=2

[Install11457493C5A56847]
Default=25xn6287.default-release
Locked=1
```

It does find the profile0 path from the default, but something is still throwing an error as above.
I did end up using the `-p` argument to manually set the path and it worked fine after.
